Repository SOPT-31st-SOPKATHON-12/SOPKATHON-iOS, pull requests merged in 2022-11, with the labels that each got.

#2 [Setting] #1- 프로젝트 세팅
  MyPooDiary/MyPooDiary.xcodeproj/project.pbxproj
  MyPooDiary/MyPooDiary.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyPooDiary/MyPooDiary.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyPooDiary/MyPooDiary.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyPooDiary/MyPooDiary/Global/Literals/ColorLiterals.swift
  MyPooDiary/MyPooDiary/Global/Literals/FontLiterals.swift
  MyPooDiary/MyPooDiary/Global/Literals/ImageLiterals.swift
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/Contents.json
  MyPooDiary/MyPooDiary/Global/Supports/AppDelegate.swift
  MyPooDiary/MyPooDiary/Global/Supports/SceneDelegate.swift
  MyPooDiary/MyPooDiary/Global/Utils/addSubviews.swift
  MyPooDiary/MyPooDiary/Global/Utils/getClassName.swift
  MyPooDiary/MyPooDiary/Info.plist
  MyPooDiary/MyPooDiary/Network/Base/APIConstants.swift
  MyPooDiary/MyPooDiary/Network/Base/Encodable+.swift
  MyPooDiary/MyPooDiary/Network/Base/NetworkLoggerPlugin.swift
  MyPooDiary/MyPooDiary/Network/DTO/ExampleRequestDto.swift
  MyPooDiary/MyPooDiary/Network/DTO/ExampleResponseDto.swift
  MyPooDiary/MyPooDiary/Network/Router/ExampleRouter.swift
  MyPooDiary/MyPooDiary/Screens/Friends/FriendsVIewController.swift
  MyPooDiary/MyPooDiary/Screens/Main/MainViewController.swift
  MyPooDiary/MyPooDiary/Screens/Report/ReportViewController.swift
Labels: 수빈 🤍, Setting

#7 [Feat]: Main view 구현
  MyPooDiary/MyPooDiary.xcodeproj/project.pbxproj
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/Order.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/Order.imageset/Order.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/Order.imageset/Order@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/Order.imageset/Order@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/friend.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/friend.imageset/icon_profile.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/friend.imageset/icon_profile@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/friend.imageset/icon_profile@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/logo.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/logo.imageset/Frame 21.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/logo.imageset/Frame 21@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/logo.imageset/Frame 21@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/rightShift.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/rightShift.imageset/Expand_left.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/rightShift.imageset/Expand_left@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/rightShift.imageset/Expand_left@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/user.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/user.imageset/Group 2875.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/user.imageset/Group 2875@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/user.imageset/Group 2875@3x.png
  MyPooDiary/MyPooDiary/Screens/Main/Cell/FriendCollectionViewCell.swift
  MyPooDiary/MyPooDiary/Screens/Main/Cell/RecordTableViewCell.swift
  MyPooDiary/MyPooDiary/Screens/Main/MainViewController.swift
  MyPooDiary/MyPooDiary/Screens/Main/Model/FriendModel.swift
  MyPooDiary/MyPooDiary/Screens/Main/Model/RecordModel.swift
Labels: 승헌 💜, Feat

#18 [Feat] #17- 서버 연결 및 뷰 수정
  MyPooDiary/MyPooDiary.xcodeproj/project.pbxproj
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-1-click.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-1-click.imageset/mdi_smiley-dead-click.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-1-click.imageset/mdi_smiley-dead-click@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-1-click.imageset/mdi_smiley-dead-click@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-1.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-1.imageset/mdi_smiley-dead.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-1.imageset/mdi_smiley-dead@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-1.imageset/mdi_smiley-dead@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-2-click.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-2-click.imageset/mdi_smiley-happy-click.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-2-click.imageset/mdi_smiley-happy-click@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-2-click.imageset/mdi_smiley-happy-click@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-2.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-2.imageset/mdi_smiley-happy.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-2.imageset/mdi_smiley-happy@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-2.imageset/mdi_smiley-happy@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-3-click.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-3-click.imageset/mdi_smiley-sad.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-3-click.imageset/mdi_smiley-sad@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-3-click.imageset/mdi_smiley-sad@3x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-3.imageset/Contents.json
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-3.imageset/mdi_smiley-sad-click.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-3.imageset/mdi_smiley-sad-click@2x.png
  MyPooDiary/MyPooDiary/Global/Resources/Assets.xcassets/RecordView/mdi_smiley-3.imageset/mdi_smiley-sad-click@3x.png
  MyPooDiary/MyPooDiary/Network/DTO/RecordRequestDto.swift
  MyPooDiary/MyPooDiary/Network/DTO/RecordResponseDto.swift
  MyPooDiary/MyPooDiary/Network/Router/RecordRouter.swift
  MyPooDiary/MyPooDiary/Screens/Main/MainViewController.swift
  MyPooDiary/MyPooDiary/Screens/Main/RecordBottomSheet.swift
  MyPooDiary/MyPooDiary/Screens/Main/RecordDetailBottomSheet.swift
Labels: 수빈 🤍, Feat

#20 [Feat] 친구 리스트 뷰, 응원하기 뷰 API 연동
  MyPooDiary/MyPooDiary.xcodeproj/project.pbxproj
  MyPooDiary/MyPooDiary/Network/DTO/FriendListResponseDto.swift
  MyPooDiary/MyPooDiary/Network/DTO/FriendStoryResponseDto.swift
  MyPooDiary/MyPooDiary/Network/Router/FriendsRouter.swift
  MyPooDiary/MyPooDiary/Screens/Friends/FriendListViewController.swift
  MyPooDiary/MyPooDiary/Screens/Friends/FriendViewController.swift
  MyPooDiary/MyPooDiary/Screens/Story/StoryViewController.swift
Labels: 의서 💚, Feat
